import { api } from '@/lib/api';
import { notFound } from 'next/navigation';
import { CopyLink } from './CopyLink';

export const dynamic = 'force-dynamic';

export default async function SharePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await api.share(id).catch(() => null);
  if (!data) return notFound();
  return (
    <main style={{ maxWidth: 760, margin: '40px auto', padding: '0 24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
        <div style={{ fontSize: 12, color: 'var(--cm-muted)', textTransform: 'uppercase', letterSpacing: 0.6 }}>
          Shared answer
        </div>
        <CopyLink id={id} />
      </div>
      <h1 style={{ fontSize: 24, fontWeight: 600, marginTop: 8 }}>{data.query}</h1>
      <article style={{ marginTop: 18, color: 'var(--cm-fg)', whiteSpace: 'pre-wrap', lineHeight: 1.65 }}>
        {data.answer}
      </article>
      <footer style={{ marginTop: 40, paddingTop: 16, borderTop: '1px solid var(--cm-border)', color: 'var(--cm-muted)', fontSize: 13 }}>
        Generated by ClawMind on this machine.
      </footer>
    </main>
  );
}
