'use client';
// Invite acceptance landing page. The invitee arrives here from the link
// generated by /settings/invitations. The token is read from the URL,
// peeked (read-only) so the user can confirm the workspace + role before
// committing, and then redeemed with a single POST. Acceptance fails
// closed if the authenticated email does not match the bound address.

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import { TopNav } from '@/components/TopNav';
import {
  api,
  ApiError,
  fmtRelative,
  type InvitationPeek,
  type MemberRole,
} from '@/lib/api';
import {
  Spinner,
  ErrorState,
  IconCheck,
  IconShield,
  IconWarning,
  IconAt,
  IconArrowRight,
} from '@clawmind/ui';

function roleLabel(r: MemberRole): string {
  switch (r) {
    case 'owner': return 'Owner';
    case 'admin': return 'Admin';
    case 'member': return 'Member';
    case 'viewer': return 'Viewer';
  }
}

function explainError(err: unknown): string {
  if (err instanceof ApiError) {
    if (err.status === 401) return 'You need to sign in first. Open the welcome page, sign in with the email this invite was sent to, then click the link again.';
    if (err.body && typeof err.body === 'object') {
      const b = err.body as { error?: string };
      if (b.error === 'email-mismatch') return 'This invite was issued to a different email. Sign in with the address it was sent to.';
      if (b.error === 'expired') return 'This invitation has expired. Ask an admin to send a new one.';
      if (b.error === 'revoked') return 'This invitation was revoked. Ask an admin to send a new one.';
      if (b.error === 'consumed') return 'This invitation was already used. If you should still have access, ask an admin.';
      if (b.error === 'not-found') return 'This invite link is not valid.';
    }
    return err.message;
  }
  return err instanceof Error ? err.message : 'something went wrong';
}

export default function AcceptInvitePage() {
  const router = useRouter();
  const params = useSearchParams();
  const token = params.get('token') ?? '';
  const [peek, setPeek] = useState<InvitationPeek | null>(null);
  const [loading, setLoading] = useState(true);
  const [peekError, setPeekError] = useState<string | null>(null);
  const [accepting, setAccepting] = useState(false);
  const [acceptError, setAcceptError] = useState<string | null>(null);
  const [accepted, setAccepted] = useState<MemberRole | null>(null);

  const load = useCallback(async () => {
    if (!token) {
      setLoading(false);
      setPeekError('Missing invite token. Open the link from your email.');
      return;
    }
    setLoading(true);
    setPeekError(null);
    try {
      const data = await api.invitationsPeek(token);
      setPeek(data);
    } catch (err) {
      setPeekError(explainError(err));
    } finally {
      setLoading(false);
    }
  }, [token]);

  useEffect(() => {
    void load();
  }, [load]);

  const accept = async () => {
    setAccepting(true);
    setAcceptError(null);
    try {
      const result = await api.invitationsAccept(token);
      setAccepted(result.assignedRole);
      setTimeout(() => router.push('/dashboard'), 1500);
    } catch (err) {
      setAcceptError(explainError(err));
    } finally {
      setAccepting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
      <TopNav />
      <main className="mx-auto max-w-xl px-4 py-10 sm:px-6 sm:py-16">
        <div className="rounded-md border border-[var(--border)] bg-[var(--surface)] p-6">
          <h1 className="flex items-center gap-2 text-xl font-semibold">
            <IconAt size={22} /> Accept invitation
          </h1>

          {loading && (
            <div className="mt-6 flex items-center gap-2 text-sm text-[var(--muted)]">
              <Spinner size={16} /> Checking your invite...
            </div>
          )}

          {!loading && peekError && (
            <div className="mt-6">
              <ErrorState title="Invite unavailable" message={peekError} onRetry={token ? load : undefined} />
              <Link
                href="/welcome"
                className="mt-4 inline-flex items-center gap-1 text-sm underline"
              >
                Back to welcome <IconArrowRight size={12} />
              </Link>
            </div>
          )}

          {!loading && peek && !accepted && (
            <>
              <p className="mt-2 text-sm text-[var(--muted)]">
                You have been invited to join this ClawMind workspace.
              </p>
              <dl className="mt-5 space-y-3 rounded-md border border-[var(--border)] bg-[var(--bg)] p-4 text-sm">
                <div className="flex items-start justify-between gap-3">
                  <dt className="text-[var(--muted)]">Email</dt>
                  <dd className="text-right font-medium">{peek.email}</dd>
                </div>
                <div className="flex items-start justify-between gap-3">
                  <dt className="text-[var(--muted)]">Role</dt>
                  <dd className="inline-flex items-center gap-1 text-right font-medium">
                    <IconShield size={13} /> {roleLabel(peek.role)}
                  </dd>
                </div>
                {peek.label && (
                  <div className="flex items-start justify-between gap-3">
                    <dt className="text-[var(--muted)]">Note</dt>
                    <dd className="text-right">{peek.label}</dd>
                  </div>
                )}
                <div className="flex items-start justify-between gap-3">
                  <dt className="text-[var(--muted)]">Expires</dt>
                  <dd className="text-right">{fmtRelative(peek.expiresAt)}</dd>
                </div>
              </dl>

              <div className="mt-5 flex items-start gap-2 rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-800 dark:text-amber-300">
                <IconWarning size={14} />
                <span>
                  You must be signed in as {peek.email}. The server verifies your authenticated email
                  against the invite before granting the role.
                </span>
              </div>

              {acceptError && (
                <div className="mt-4 rounded-md border border-rose-500/30 bg-rose-500/5 px-3 py-2 text-sm text-rose-700 dark:text-rose-400">
                  {acceptError}
                </div>
              )}

              <div className="mt-5 flex flex-col gap-2 sm:flex-row">
                <button
                  type="button"
                  onClick={accept}
                  disabled={accepting}
                  className="inline-flex items-center justify-center gap-1.5 rounded-md bg-[var(--fg)] px-3 py-2 text-sm font-medium text-[var(--bg)] disabled:opacity-50"
                >
                  {accepting ? <Spinner size={14} /> : <IconCheck size={14} />} Accept and join
                </button>
                <Link
                  href="/welcome"
                  className="inline-flex items-center justify-center rounded-md border border-[var(--border)] px-3 py-2 text-sm hover:bg-[var(--surface)]"
                >
                  Not me
                </Link>
              </div>
            </>
          )}

          {accepted && (
            <div className="mt-6 rounded-md border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm text-emerald-800 dark:text-emerald-300">
              <div className="flex items-center gap-1.5 font-medium">
                <IconCheck size={16} /> Welcome aboard
              </div>
              <p className="mt-1 text-emerald-700/80 dark:text-emerald-300/80">
                You now have {roleLabel(accepted).toLowerCase()} access. Redirecting...
              </p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
